### ISSUE TITLE
The category entry in create product isn't actually updating data in database.

### ISSUE THREAD

**Issue by starkshaw** [SprintFire/marketplace#101]
Found out during the demo.

**Comment by starkshaw** [comment]
I tested few more times, the problem is when I enter the edit view the category entry isn't get the data from database.

**Comment by danielpaul** [comment]
@starkshaw could you have a look at this and resolve it please? From my guess it's something to do with the way we are getting the category in the controller.

**Comment by starkshaw** [comment]
@danielpaul I'll have a look.

**Comment by starkshaw** [comment]
Fixed, creating Pull Request.
