### ISSUE TITLE
Category view in Active Admin is not working.

### ISSUE THREAD

**Issue by starkshaw** [SprintFire/marketplace#102]
The error messages seem irrelevant.

```
Collection is not a paginated scope. Set collection.page(params[:page]).per(10) before calling :paginated_collection.
```

**Comment by danielpaul** [comment]
@starkshaw have a look at this: http://stackoverflow.com/questions/12033944/rails-3-2-activeadmin-collection-is-not-a-paginated-scope-error

Adding the default scope might fix it.

**Comment by danielpaul** [comment]
Or naming it like in some of the other answers there.

**Comment by starkshaw** [comment]
Fixed. Creating Pull Request.
