### ISSUE TITLE
Phone number should NOT be NUMERIC!

### ISSUE THREAD

**Issue by starkshaw** [SprintFire/marketplace#33]
In database the leading 0 will not save

E.g. 0871234567 will save as 871234567 in database.

**Comment by danielpaul** [comment]
Agreed. Let's change the DB structure to be a sting but validate a number via rails validations.

**Comment by starkshaw** [comment]
@danielpaul in addition, should the longitude and latitude be string too?

**Comment by danielpaul** [comment]
@starkshaw You could save it in the same column as an array.

`add_column :shops, :location, :decimal, array: true`

**Comment by starkshaw** [comment]
But latitude and longitude are 2 columns, how can I send to database?

**Comment by danielpaul** [comment]
From the two values, you can combine them to an array and then save. You can do this with a filter before saving and updating. Something like this: 

`@shop.location = [shop_params[:lat], shop_params[:lng]]`

You would need to still have lat, lng as `attr_accessor` tho on the model.

**Comment by starkshaw** [comment]
I think just keep it clear, because I think it is really easy to mess latitude and longitude up.
Numeric is working fine now.

**Comment by starkshaw** [comment]
Plus I don't know how to do equivalence of

```
= f.hidden_field :latitude
= f.hidden_field :longitude
```

for an array.

**Comment by danielpaul** [comment]
It's fine for now but in the very near future might need to refactor based on if it is easier to do search with one column or with two.

**Comment by danielpaul** [comment]
@starkshaw This issue is resolved right?

**Comment by starkshaw** [comment]
Oh yep. 
Notice that `rake db:migrate` is required.

**Comment by danielpaul** [comment]
Okey cool. Thnx.
