### ISSUE TITLE
Category database can't be empty, existed products with no category selected will not be able to edit.

### ISSUE THREAD

**Issue by starkshaw** [SprintFire/marketplace#89]
- Category database cannot be empty as stated in the title.
- Category database must be filled though Active Admin.
- Error of editing an existed product with no category selected is

```
undefined method `collect' for nil:NilClass
```

**Comment by danielpaul** [comment]
Solution for this could be by default there is a category "uncategorized" which all products belong to by default.

**Comment by starkshaw** [comment]
@danielpaul Then just add a seed to the database. @LevinGeorge You want to do it or I take over?

**Comment by starkshaw** [comment]
Fixed.
